{% set name = "napari-simpleitk-image-processing" %}
{% set version = "0.2.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-simpleitk-image-processing-{{ version }}.tar.gz
  sha256: 3b58a9b2f76e6954d4b9c8df9ace1a5965bcefb7abade8b1513dd0c5681a2d5d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - napari-plugin-engine >=0.1.4
    - napari-skimage-regionprops
    - napari-time-slicer
    - napari-tools-menu
    - numpy
    - python >=3.7
    - simpleitk
    - napari-assistant

test:
  imports:
    - napari_simpleitk_image_processing
  commands:
    - pip list
    # - pip check
  requires:
    - pip

about:
  home: https://github.com/haesleinhuepf/napari-simpleitk-image-processing
  summary: Process and analyze images using SimpleITK in napari
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/napari
    - haesleinhuepf
