{% set name = "napari-simpleitk-image-processing" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-simpleitk-image-processing-{{ version }}.tar.gz
  sha256: efc30c6d57e86bb76ff61d444eeeab3371df1c90bbd3b3df6503449e80ca929b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - napari-plugin-engine >=0.1.4
    - napari-skimage-regionprops >=0.5.1
    - napari-time-slicer
    - napari-tools-menu
    - numpy
    - python >=3.7
    - simpleitk
    - napari-assistant
    - toolz
    - napari

test:
  imports:
    - napari_simpleitk_image_processing
  commands:
    - pip list
    # - pip check
  requires:
    - pip

about:
  home: https://github.com/haesleinhuepf/napari-simpleitk-image-processing
  summary: Process and analyze images using SimpleITK in napari
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/napari
    - haesleinhuepf
