{% set name = "napari-simpleitk-image-processing" %}
{% set version = "0.4.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-simpleitk-image-processing-{{ version }}.tar.gz
  sha256: b690d38aa67cdce3ae9e9b38f5ea98aa2bb3fcfb7b41943c56c68ed5df70ba3c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - napari-plugin-engine >=0.1.4
    - napari-skimage-regionprops >=0.5.1
    - napari-time-slicer
    - napari-tools-menu >=0.1.17
    - numpy
    - python >=3.7
    - simpleitk
    - napari-assistant >=0.3.10
    - toolz
    - napari
    - stackview >=0.3.2

test:
  imports:
    - napari_simpleitk_image_processing
  commands:
    - pip list
    # - pip check
  requires:
    - pip

about:
  home: https://github.com/haesleinhuepf/napari-simpleitk-image-processing
  summary: Process and analyze images using SimpleITK in napari
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - haesleinhuepf
